### ISSUE TITLE
[feature] add Global Type definition

### ISSUE THREAD

**Issue by TechQuery** [wessberg/intl-list-format#2]
Type definition as shown below will be help to **TypeScript** coders:

```TypeScript
declare namespace Intl {
  class ListFormat {
    constructor(locales: string, options?: Record<string, any>);
    format(items: string[]): string;
  }
}
```

**Comment by wessberg** [comment]
Hey there.

If a polyfill such as this one extend the type definitions for a global built-in object such as the `Intl` namespace, then problems will arise due to conflicting definitions the day TypeScript itself ships typings for `ListFormat`, which TypeScript definitely will in time given that the built-in lib definitions are auto-generated based on the Ecma and HTML specs. To avoid this problem, I don't think it would be a good idea to ship typings that extend the global `Intl` object.
